### ISSUE TITLE
error con orionxapi/lib/dsl.py"

### ISSUE THREAD

**Issue by nijirija** [itolosa/orionx-api-client#3]
Hola!

Intentando usar el connection manager recibo el siguiente error:

```
Traceback (most recent call last):
  File "orionx_marginator2.py", line 1, in <module>
    from orionxapi.connection_manager import client, orionxapi_builder
  File "/Users/nijirija/Library/Python/2.7/lib/python/site-packages/orionxapi/connection_manager.py", line 8, in <module>
    from .lib.dsl import DSLSchema
  File "/Users/nijirija/Library/Python/2.7/lib/python/site-packages/orionxapi/lib/dsl.py", line 154
    def query(*fields, operation='query'):
                               ^
SyntaxError: invalid syntax

```

Se te ocurre qué puede ser?

Estoy con python 2.7 en Mac

Gracias!

**Comment by itolosa** [comment]
Arreglado en version 0.1.1. Usa `pip install --upgrade orionx-api-client` para actualizar la version instalada
