### ISSUE TITLE
Nombres/parámetros de las queries disponibles para DSL

### ISSUE THREAD

**Issue by nijirija** [itolosa/orionx-api-client#9]
Hola, estoy intentando usar este esquema para las queries, pero no esto seguro qué debería tomar como nombre de la query ni en al final en el .open

```
ds = DSLSchema(client)

query_dsl = ds.Query.marketStats.args(
                marketCode="CHACLP",
                aggregation="h1"
              ).select(ds.MarketStatsPoint.open)

print(ds.query(query_dsl))
```

Me funciona impeque el ejemplo, pero intentando seguir el esquema usando los nombres de las queries que están en examples/queries.graphql, siempre me falla:

```
Traceback (most recent call last):
  File "orionx_marginator3.py", line 24, in <module>
    ).select(ds.CurrenciesPoint.open)
  File "/usr/local/lib/python3.6/site-packages/pygql/dsl.py", line 45, in __getattr__
    formatted_name, field_def = self.get_field(name)
  File "/usr/local/lib/python3.6/site-packages/pygql/dsl.py", line 51, in get_field
    if name in self.type.fields:
AttributeError: 'NoneType' object has no attribute 'fields'
```

¿Qué debería estar usando?

**Comment by itolosa** [comment]
Prueba actualizando la librería a la última versión
```bash
$ sudo pip install orionx-api-client --upgrade
```

**Comment by itolosa** [comment]
alguna novedad?
